-- MySQL Script generated by MySQL Workbench
-- Wed Nov  3 09:45:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Sin_Gluten
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Sin_Gluten` ;

-- -----------------------------------------------------
-- Schema Sin_Gluten
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sin_Gluten` DEFAULT CHARACTER SET utf8 ;
USE `Sin_Gluten` ;

-- -----------------------------------------------------
-- Table `Sin_Gluten`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sin_Gluten`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Usuario` VARCHAR(100) NOT NULL,
  `Fecha_Nacimiento` DATE NULL,
  `Pais` VARCHAR(150) NOT NULL,
  `Provincia` VARCHAR(150) NOT NULL,
  `Contraseña` VARCHAR(150) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sin_Gluten`.`Recetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sin_Gluten`.`Recetas` (
  `idRecetas` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) NOT NULL,
  `Ingredientes` TEXT(1000) NULL,
  `Preparacion` TEXT(1000) NULL,
  PRIMARY KEY (`idRecetas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sin_Gluten`.`Organizador_Semanal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sin_Gluten`.`Organizador_Semanal` (
  `idOrganizador_Semanal` INT NOT NULL AUTO_INCREMENT,
  `Dia` VARCHAR(45) NOT NULL,
  `Fecha` DATE NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Recetas_idRecetas` INT NOT NULL,
  PRIMARY KEY (`idOrganizador_Semanal`, `Usuario_idUsuario`, `Recetas_idRecetas`),
  CONSTRAINT `fk_Organizador_Semanal_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Sin_Gluten`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organizador_Semanal_Recetas1`
    FOREIGN KEY (`Recetas_idRecetas`)
    REFERENCES `Sin_Gluten`.`Recetas` (`idRecetas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Organizador_Semanal_Usuario_idx` ON `Sin_Gluten`.`Organizador_Semanal` (`Usuario_idUsuario` ASC) VISIBLE;

CREATE INDEX `fk_Organizador_Semanal_Recetas1_idx` ON `Sin_Gluten`.`Organizador_Semanal` (`Recetas_idRecetas` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
